name: Auto-Generate Docs
on:
  push:
    branches: [main]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dineshsonachalam/markdown-autodocs@v1.0.0
        with:
          source: "province*.json"  # Your JSON files
          template: "README.md"     # File to update
