name: Generate README
on:
  push:
    branches: [main]  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt  # If your script needs packages
      - name: Run script to generate README
        run: python generate_readme.py
      - name: Commit updated README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate README.md"
          file_pattern: "README.md"
